//! AutoFiler processor for suggesting document organisation.
//!
//! This processor suggests destination folders, object types, tags,
//! templates, and filenames for knowledge objects before they reach
//! permanent storage. Users retain final approval — nothing moves
//! automatically without confirmation.
//!
//! # Architecture
//!
//! ```text
//! KnowledgeObject
//!     ↓ AutoFiler
//! KnowledgeObject with suggestions in metadata.custom
//!   - suggested_folder
//!   - suggested_tags
//!   - suggested_template
//!   - suggested_filename
//!   - suggested_object_type
//! ```

use crate::models::knowledge_object::{KnowledgeObject, ObjectType};
use crate::processing::processor::{ProcessingDecision, ProcessingResult, Processor};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Processor that suggests organisation for knowledge objects.
///
/// The AutoFiler adds suggestions to the object's metadata without
/// modifying the object itself. Suggestions include:
/// - Destination folder
/// - Tags
/// - Template
/// - Filename
/// - Object type
///
/// All suggestions are stored in `metadata.custom` under the key
/// `"auto_file_suggestions"` and require user confirmation before
/// any action is taken.
#[derive(Debug, Default)]
pub struct AutoFiler {
    /// Default folder for unclassified documents.
    pub default_folder: String,
    /// Known folder mappings by object type.
    pub folder_mappings: HashMap<ObjectType, String>,
    /// Known tag mappings by object type.
    pub tag_mappings: HashMap<ObjectType, Vec<String>>,
    /// Known template mappings by object type.
    pub template_mappings: HashMap<ObjectType, String>,
}

/// Suggestions generated by the AutoFiler.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AutoFileSuggestions {
    /// Suggested destination folder path.
    pub suggested_folder: Option<String>,
    /// Suggested tags.
    pub suggested_tags: Vec<String>,
    /// Suggested template name.
    pub suggested_template: Option<String>,
    /// Suggested filename.
    pub suggested_filename: Option<String>,
    /// Suggested object type.
    pub suggested_object_type: Option<String>,
    /// Confidence of the suggestions (0.0 - 1.0).
    pub confidence: f64,
}

impl AutoFiler {
    pub fn new() -> Self {
        let mut folder_mappings = HashMap::new();
        folder_mappings.insert(ObjectType::Invoice, "Invoices".to_string());
        folder_mappings.insert(ObjectType::Receipt, "Receipts".to_string());
        folder_mappings.insert(ObjectType::Meeting, "Meetings".to_string());
        folder_mappings.insert(ObjectType::Contract, "Contracts".to_string());
        folder_mappings.insert(ObjectType::ResearchPaper, "Research".to_string());
        folder_mappings.insert(ObjectType::Resume, "Resumes".to_string());
        folder_mappings.insert(ObjectType::Manual, "Manuals".to_string());
        folder_mappings.insert(ObjectType::Presentation, "Presentations".to_string());
        folder_mappings.insert(ObjectType::Article, "Articles".to_string());
        folder_mappings.insert(ObjectType::Letter, "Letters".to_string());
        folder_mappings.insert(ObjectType::Image, "Images".to_string());
        folder_mappings.insert(ObjectType::Screenshot, "Screenshots".to_string());
        folder_mappings.insert(ObjectType::Scan, "Scans".to_string());
        folder_mappings.insert(ObjectType::Pdf, "Documents".to_string());
        folder_mappings.insert(ObjectType::Video, "Videos".to_string());
        folder_mappings.insert(ObjectType::AudioRecording, "Audio".to_string());
        folder_mappings.insert(ObjectType::Repository, "Repositories".to_string());
        folder_mappings.insert(ObjectType::Website, "Web".to_string());
        folder_mappings.insert(ObjectType::Bookmark, "Bookmarks".to_string());
        folder_mappings.insert(ObjectType::Person, "People".to_string());
        folder_mappings.insert(ObjectType::Organisation, "Organisations".to_string());
        folder_mappings.insert(ObjectType::Project, "Projects".to_string());
        folder_mappings.insert(ObjectType::Book, "Books".to_string());
        folder_mappings.insert(ObjectType::Course, "Courses".to_string());

        let mut tag_mappings = HashMap::new();
        tag_mappings.insert(ObjectType::Invoice, vec!["finance".to_string(), "invoice".to_string()]);
        tag_mappings.insert(ObjectType::Receipt, vec!["finance".to_string(), "receipt".to_string()]);
        tag_mappings.insert(ObjectType::Meeting, vec!["meeting".to_string(), "notes".to_string()]);
        tag_mappings.insert(ObjectType::Contract, vec!["legal".to_string(), "contract".to_string()]);
        tag_mappings.insert(ObjectType::ResearchPaper, vec!["research".to_string(), "academic".to_string()]);
        tag_mappings.insert(ObjectType::Resume, vec!["career".to_string(), "resume".to_string()]);
        tag_mappings.insert(ObjectType::Manual, vec!["reference".to_string(), "guide".to_string()]);
        tag_mappings.insert(ObjectType::Presentation, vec!["presentation".to_string(), "slides".to_string()]);
        tag_mappings.insert(ObjectType::Article, vec!["article".to_string(), "reading".to_string()]);
        tag_mappings.insert(ObjectType::Letter, vec!["correspondence".to_string(), "letter".to_string()]);
        tag_mappings.insert(ObjectType::Image, vec!["image".to_string()]);
        tag_mappings.insert(ObjectType::Screenshot, vec!["screenshot".to_string()]);
        tag_mappings.insert(ObjectType::Scan, vec!["scan".to_string()]);
        tag_mappings.insert(ObjectType::Pdf, vec!["pdf".to_string(), "document".to_string()]);
        tag_mappings.insert(ObjectType::Video, vec!["video".to_string()]);
        tag_mappings.insert(ObjectType::AudioRecording, vec!["audio".to_string()]);
        tag_mappings.insert(ObjectType::Repository, vec!["code".to_string(), "repository".to_string()]);
        tag_mappings.insert(ObjectType::Website, vec!["web".to_string()]);
        tag_mappings.insert(ObjectType::Bookmark, vec!["bookmark".to_string()]);
        tag_mappings.insert(ObjectType::Person, vec!["contact".to_string(), "person".to_string()]);
        tag_mappings.insert(ObjectType::Organisation, vec!["contact".to_string(), "organisation".to_string()]);
        tag_mappings.insert(ObjectType::Project, vec!["project".to_string()]);
        tag_mappings.insert(ObjectType::Book, vec!["reading".to_string(), "book".to_string()]);
        tag_mappings.insert(ObjectType::Course, vec!["learning".to_string(), "course".to_string()]);

        let mut template_mappings = HashMap::new();
        template_mappings.insert(ObjectType::Invoice, "invoice".to_string());
        template_mappings.insert(ObjectType::Receipt, "receipt".to_string());
        template_mappings.insert(ObjectType::Meeting, "meeting_note".to_string());
        template_mappings.insert(ObjectType::Contract, "contract".to_string());
        template_mappings.insert(ObjectType::ResearchPaper, "research_paper".to_string());
        template_mappings.insert(ObjectType::Resume, "resume".to_string());
        template_mappings.insert(ObjectType::Manual, "manual".to_string());
        template_mappings.insert(ObjectType::Presentation, "presentation".to_string());
        template_mappings.insert(ObjectType::Article, "article".to_string());
        template_mappings.insert(ObjectType::Letter, "letter".to_string());
        template_mappings.insert(ObjectType::Note, "note".to_string());
        template_mappings.insert(ObjectType::Document, "document".to_string());

        Self {
            default_folder: "Inbox".to_string(),
            folder_mappings,
            tag_mappings,
            template_mappings,
        }
    }

    /// Generate suggestions for a knowledge object.
    pub fn suggest(&self, obj: &KnowledgeObject) -> AutoFileSuggestions {
        let mut suggestions = AutoFileSuggestions {
            suggested_folder: None,
            suggested_tags: Vec::new(),
            suggested_template: None,
            suggested_filename: None,
            suggested_object_type: None,
            confidence: 0.0,
        };

        let mut signal_count = 0;

        // 1. Suggest folder based on object type
        if let Some(folder) = self.folder_mappings.get(&obj.object_type) {
            suggestions.suggested_folder = Some(folder.clone());
            signal_count += 1;
        }

        // 2. Suggest tags based on object type
        if let Some(tags) = self.tag_mappings.get(&obj.object_type) {
            // Only add tags that aren't already present
            for tag in tags {
                if !suggestions.suggested_tags.contains(tag) {
                    suggestions.suggested_tags.push(tag.clone());
                }
            }
            signal_count += 1;
        }

        // 3. Suggest template based on object type
        if let Some(template) = self.template_mappings.get(&obj.object_type) {
            suggestions.suggested_template = Some(template.clone());
            signal_count += 1;
        }

        // 4. Suggest filename based on source file or title
        if let Some(source_file) = &obj.metadata.source_file {
            if let Some(file_name) = std::path::Path::new(source_file)
                .file_name()
                .and_then(|n| n.to_str())
            {
                suggestions.suggested_filename = Some(file_name.to_string());
                signal_count += 1;
            }
        } else if let Some(title) = &obj.metadata.title {
            let safe_filename = title
                .chars()
                .map(|c| if c.is_alphanumeric() || c == ' ' { c } else { '_' })
                .collect::<String>()
                .trim()
                .to_string();
            if !safe_filename.is_empty() {
                suggestions.suggested_filename = Some(format!("{}.md", safe_filename));
                signal_count += 1;
            }
        }

        // 5. Suggest object type if it was classified
        if let Some(classification) = obj.metadata.custom.get("classification") {
            if let Some(obj_type_str) = classification.get("object_type").and_then(|v| v.as_str()) {
                suggestions.suggested_object_type = Some(obj_type_str.to_string());
                signal_count += 1;
            }
        }

        // 6. Check existing tags in custom metadata for additional suggestions
        if let Some(existing_tags) = obj.metadata.custom.get("tags") {
            if let Some(tags_arr) = existing_tags.as_array() {
                for tag in tags_arr {
                    if let Some(tag_str) = tag.as_str() {
                        if !suggestions.suggested_tags.contains(&tag_str.to_lowercase()) {
                            suggestions.suggested_tags.push(tag_str.to_lowercase());
                        }
                    }
                }
            }
        }

        // Calculate confidence based on number of signals
        suggestions.confidence = if signal_count > 0 {
            (signal_count as f64) / 5.0
        } else {
            0.0
        };

        suggestions
    }
}

impl Processor for AutoFiler {
    fn name(&self) -> &'static str {
        "auto_filer"
    }

    fn process(&self, mut knowledge_object: KnowledgeObject) -> ProcessingResult {
        let suggestions = self.suggest(&knowledge_object);

        // Store suggestions in custom metadata
        knowledge_object.metadata.custom.insert(
            "auto_file_suggestions".to_string(),
            serde_json::to_value(&suggestions).unwrap_or(serde_json::Value::Null),
        );

        let warnings = if suggestions.confidence > 0.5 {
            vec![format!(
                "Auto-file suggestions generated (confidence {:.0}%): folder={:?}, tags={:?}",
                suggestions.confidence * 100.0,
                suggestions.suggested_folder,
                suggestions.suggested_tags
            )]
        } else {
            vec!["Auto-file suggestions: low confidence, manual review recommended".to_string()]
        };

        ProcessingResult::modified(knowledge_object, warnings)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::knowledge_object::{ObjectContent, ObjectMetadata, ObjectType};
    use uuid::Uuid;

    fn create_test_object(object_type: ObjectType) -> KnowledgeObject {
        KnowledgeObject {
            id: Uuid::new_v4(),
            object_type,
            vault_id: "test-vault".to_string(),
            created_at: "2024-01-01T00:00:00Z".to_string(),
            modified_at: "2024-06-01T00:00:00Z".to_string(),
            content: ObjectContent::PlainText,
            metadata: ObjectMetadata::default(),
        }
    }

    #[test]
    fn filer_suggests_invoice_folder() {
        let filer = AutoFiler::new();
        let obj = create_test_object(ObjectType::Invoice);

        let suggestions = filer.suggest(&obj);
        assert_eq!(suggestions.suggested_folder, Some("Invoices".to_string()));
        assert!(suggestions.suggested_tags.contains(&"finance".to_string()));
        assert_eq!(suggestions.suggested_template, Some("invoice".to_string()));
    }

    #[test]
    fn filer_suggests_meeting_folder() {
        let filer = AutoFiler::new();
        let obj = create_test_object(ObjectType::Meeting);

        let suggestions = filer.suggest(&obj);
        assert_eq!(suggestions.suggested_folder, Some("Meetings".to_string()));
        assert!(suggestions.suggested_tags.contains(&"meeting".to_string()));
    }

    #[test]
    fn filer_suggests_filename_from_source() {
        let filer = AutoFiler::new();
        let mut obj = create_test_object(ObjectType::Note);
        obj.metadata.source_file = Some("/path/to/my-note.md".to_string());

        let suggestions = filer.suggest(&obj);
        assert_eq!(suggestions.suggested_filename, Some("my-note.md".to_string()));
    }

    #[test]
    fn filer_suggests_filename_from_title() {
        let filer = AutoFiler::new();
        let mut obj = create_test_object(ObjectType::Note);
        obj.metadata.title = Some("My Important Note".to_string());

        let suggestions = filer.suggest(&obj);
        assert!(suggestions.suggested_filename.is_some());
        assert!(suggestions.suggested_filename.unwrap().contains("My_Important_Note"));
    }

    #[test]
    fn filer_returns_default_for_unknown_type() {
        let filer = AutoFiler::new();
        let obj = create_test_object(ObjectType::Attachment);

        let suggestions = filer.suggest(&obj);
        assert_eq!(suggestions.suggested_folder, None);
        assert!(suggestions.suggested_tags.is_empty());
        assert_eq!(suggestions.confidence, 0.0);
    }

    #[test]
    fn processor_adds_suggestions_to_metadata() {
        let filer = AutoFiler::new();
        let obj = create_test_object(ObjectType::Invoice);

        let result = filer.process(obj);
        assert!(result.modified);
        assert!(result.knowledge_object.metadata.custom.contains_key("auto_file_suggestions"));
    }

    #[test]
    fn suggestions_deduplicate_tags() {
        let filer = AutoFiler::new();
        let mut obj = create_test_object(ObjectType::Invoice);
        // Add a tag that would also be suggested
        obj.metadata.tags = vec!["finance".to_string()];

        let suggestions = filer.suggest(&obj);
        // The finance tag should only appear once
        assert_eq!(suggestions.suggested_tags.iter().filter(|t| t == &&"finance".to_string()).count(), 1);
    }
}
