pub mod browser;
pub mod clipboard_config;
pub mod clipboard_handler;
pub mod clipboard_monitor;
pub mod engine;
pub mod file_drop_handler;
pub mod handler;
pub mod ingestion_request;
pub mod ingestion_result;
pub mod normaliser;
pub mod pipeline;
pub mod rich_browser;
pub mod screenshot_handler;
pub mod types;
pub mod utils;
pub mod watch_folder;
pub mod watch_folder_config;
pub mod watch_folder_service;

pub use browser::BrowserCaptureHandler;
pub use clipboard_config::{ClipboardMonitorConfig, ClipboardMonitorMode};
pub use clipboard_handler::ClipboardHandler;
pub use clipboard_monitor::ClipboardMonitor;
pub use engine::CaptureEngine;
pub use file_drop_handler::FileDropHandler;
pub use handler::CaptureHandler;
pub use ingestion_request::{IngestionOptions, IngestionRequest};
pub use ingestion_result::{IngestionResult, IngestionStatus};
pub use normaliser::Normaliser;
pub use pipeline::IngestionPipeline;
pub use rich_browser::{ArticleCaptureHandler, GitHubRepositoryHandler, YouTubeCaptureHandler};
pub use screenshot_handler::{ScreenshotHandler, ScreenshotMode};
pub use types::{CaptureError, CaptureRequest, CaptureResult};
pub use watch_folder::WatchFolderHandler;
pub use watch_folder_config::{ImportFolder, WatchFolderConfig};
pub use watch_folder_service::WatchFolderService;
